### handling imbalanced data set through 2 techniques
    handle it so that our model to not get baised (on one sided data samples)
1 . up sampling 
2 . down sampling

In [12]:
import numpy as np 
import pandas as pd

#random.seed ,It makes random numbers repeat the same way every time you run the code.
np.random.seed(123)

#creating a data frame with 2 classes 

n_samples = 1000
class_0_ratio= 0.9  #here is this imbalanced dataset 900 data points here and only 100 in class 1 
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - class_0_ratio #1000 - 900 = 100 in class 1

In [ ]:
#CREATING AN DATAFRAME OF IMBALANCED DATASET
import numpy as np
import pandas as pd

# Number of samples per class (imbalanced)
n_class_0 = 900
n_class_1 = 100

# Create class 0 data
df_class_0 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=n_class_0),
    "feature_2": np.random.normal(loc=0, scale=1, size=n_class_0),
    "target": np.zeros(n_class_0, dtype=int)
})

# Create class 1 data
df_class_1 = pd.DataFrame({
    "feature_1": np.random.normal(loc=2, scale=1, size=n_class_1),
    "feature_2": np.random.normal(loc=2, scale=1, size=n_class_1),
    "target": np.ones(n_class_1, dtype=int)
})

"""np.random.normal() generates numbers from a normal distribution
loc=0 → mean = 0
scale=1 → standard deviation = 1
Combine both classes into one dataset"""

df = pd.concat([df_class_0, df_class_1], ignore_index=True)

# Optional: shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df.head()

   feature_1  feature_2  target
0  -0.726114  -0.447084       0
1  -0.060794   0.069403       0
2  -0.284247  -0.863223       0
3  -1.271747  -0.173474       0
4   0.325464  -1.665280       0

### UPSAMPLING 
here we will make that 100 to 900 upscale the minority quantity value

In [14]:
df_minority= df[df['target']== 1]
df_majority= df[df['target']== 0]

## What each parameter does:

df_minority → dataset to resample

replace=True → allows duplicate rows

n_samples=900 → increase minority class from 100 → 900

random_state=42 → reproducible resampling

 ** This copies minority samples randomly until they match majority size **

In [ ]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority, replace = True ,
n_samples= len(df_majority),
random_state= 42 
)

#n_samples=len(df_majority) means n_sample = 900 , makes minority = majority

In [16]:
df_minority_upsampled.shape

(900, 3)

In [17]:
df_minority_upsampled.head()

     feature_1  feature_2  target
503   2.157959   1.613304       1
872   2.810326   3.604614       1
133   1.376371   2.845701       1
654   2.917884   3.508705       1
605   2.397060   0.740228       1